version: "3.7"
services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./configs:/etc/nginx/conf.d
      - ./src:/src
      - ./logs/:/var/log/nginx/
    networks:
      default:
        aliases:
          - nginx
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    
  php:
    build:
      context: .
      dockerfile: dockerfile
    container_name: php
    volumes:
      - ./src:/src
    working_dir: /src
    ports:
      - 8000:8000
    networks:
      default:
         aliases:
          - php
  
networks:
  default: